apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argocd-namespace.yaml
- install.yaml

patches:
  - path: argocd-server-nodeport-patch.yaml
    target:
      name: argocd-server
      kind: Service