apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-argocd
  namespace: argocd
spec:
  source:
    path: argocd/kustomize
    repoURL: https://github.com/ludovici96/devops.git
    targetRevision: HEAD
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true