version: '3.9'

services:
  website:
    image: test-dev:latest
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=cGFzc3dvcmQxMjM=
    networks:
      - app-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
