apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: alisi18/flask-example:latest
        ports:
        - containerPort: 5000
        - containerPort: 5001
        env:
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_NAME
          value: "postgres"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "cGFzc3dvcmQxMjM="
           #
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      #
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30003 # Change this port to the desired NodePort value
  type: NodePort
