name: Docker Build and Push

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Get commit count
      id: commit_count
      run: echo "::set-output name=count::$(git rev-list --count HEAD)"

    - name: Set semantic version
      id: semantic_version
      run: |
        major_version="1"
        minor_version="0"
        patch_version="${{ steps.commit_count.outputs.count }}"
        echo "::set-output name=version::$major_version.$minor_version.$patch_version"

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./flask-example
        push: true
        tags: |
          alisi18/flask-example:${{ steps.semantic_version.outputs.version }}
          alisi18/flask-example:latest
