name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-flask
      working-directory: flask-example

    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          pg_isready -U postgres -h localhost && echo Success && exit 0
          echo "Waiting for PostgreSQL ($i)..."
          sleep 5
        done
        echo "PostgreSQL not ready, giving up."
        exit 1

    - name: Run tests
      run: |
        pytest test_app.py
      working-directory: flask-example
      env:
        DATABASE_HOST: localhost
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_NAME: testdb
